# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.2.10"
kotlinxSerializationJSON = "1.9.0"
kotlinxCoroutines = "1.10.2"
kotlinxIO = "0.8.0"
ktor = "3.2.3"
kmpBigNum = "0.3.10"
crypto = "0.5.0"
kermit = "2.0.8"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxIO = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIO" }

ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientCIO = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorSerializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

kmpBigNum = { module = "com.ionspin.kotlin:bignum", version.ref = "kmpBigNum" }

cryptoCore = { module = "dev.whyoleg.cryptography:cryptography-core", version.ref = "crypto" }
cryptoProviderOptimal = { module = "dev.whyoleg.cryptography:cryptography-provider-optimal", version.ref = "crypto" }

kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

[bundles]
crypto = ["cryptoCore", "cryptoProviderOptimal"]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }