name: Build Yogurt JVM Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Cache gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/libs.versions.toml') }}

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Build yogurt-jvm fat jar
        run: ./gradlew :yogurt-jvm:buildFatJar --no-daemon

      - name: Upload fat jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: yogurt-jvm
          path: yogurt-jvm/build/libs/yogurt-jvm-all.jar
